Cash/Models/Account.cs
using System;

namespace Cash.Models
{
    /// <summary>
    /// Счёт.
    /// </summary>
    public class Account : Entity
    {
        public virtual String Title { get; set; }
    }
}

Cash/Models/CashflowRecord.cs
using System;

namespace Cash.Models
{
    /// <summary>
    /// Запись.
    /// </summary>
    public class CashflowRecord : Entity
    {
        public virtual Account Account { get; set; }
        public virtual Category Category { get; set; }
        public virtual decimal Amount { get; set; }
        public virtual DateTime DateTime { get; set; }
        public virtual String Comments { get; set; }
    }
}

Cash/Models/Category.cs
using System;

namespace Cash.Models
{
    /// <summary>
    /// Категория.
    /// </summary>
    public class Category: Entity
    {
        public virtual String Title { get; set; }
        public virtual Category ParentCategory { get; set; }
    }
}

Cash/Models/Entity.cs
using System;

namespace Cash.Models
{
    /// <summary>
    /// Сущность. Абстрактный класс, базовый для всех моделей.
    /// </summary>
    public abstract class Entity
    {
        public virtual Guid Id { get; protected set; }
    }
}

Cash/Controllers/AccountController.cs
using System.Web.Mvc;
using Cash.Models;
using Cash.Repositories;
using NHibernate;

namespace Cash.Controllers
{
    public class AccountController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Submit(string title)
        {

            // Сохранение данных в БД
            using (ISession session = NHibernateHelper.OpenSession())
            using (ITransaction transaction = session.BeginTransaction())
            {
                var newAccount = new Account
                {
                    Title = title
                };

                session.Save(newAccount);
                transaction.Commit();
            }

            // Чтение данных из БД
            var allAccounts = NHibernateHelper
                .OpenSession()
                .QueryOver<Account>()
                .List<Account>();

            return View("List", allAccounts);
        }
    }
}

Cash/Controllers/HomeController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Web.Mvc;
using Cash.Models;

namespace Cash.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Просмотр списка записей.
        /// </summary>
        public ActionResult List()
        {
            IList<CashflowRecord> model = CreateFakeData(); 
            return View(model);
        }

        private IList<CashflowRecord> CreateFakeData()
        {
            var fakeData = new List<CashflowRecord>();
            
            fakeData.Add(new CashflowRecord
            {
                Amount = 1234m,
                DateTime = DateTime.Now,
                Category = new Category { Title = "Провеочная категория" },
                Account = new Account {Title = "Наличные"},
                Comments = "Тестовый комментарий"
            });
            
            return fakeData;
        }
    }
}

Cash/Controllers/RecordController.cs
using System.Web.Mvc;

namespace Cash.Controllers
{
    public class RecordController: Controller
    {
        public ActionResult Add()
        {
            return View(); // Если не указан параметр, имя view совпадает с именем метода (в данном случае - "Add")
        }

        public ActionResult Edit()
        {
            return Content("Не реализовано");
        }

        public ActionResult Delete()
        {
            return Content("Не реализовано");
        }
    }
}

Cash/Controllers/SettingsController.cs
using System.Web.Mvc;

namespace Cash.Controllers
{
    /// <summary>
    /// Настройки.
    /// </summary>
    public class SettingsController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Cash/Controllers/StatisticsController.cs
using System.Web.Mvc;

namespace Cash.Controllers
{
    public class StatisticsController: Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Print()
        {
            return Content("Печать не реализована!");
        }
    }
}

Cash/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Paraplaner Cash WebApp";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Paraplaner Cash WebApp (это Views/Home/Index.cshtml)</h2>

<li>
    <ul>@Html.ActionLink("Просмотр списка записей", "List", "Home")</ul>
    <ul>@Html.ActionLink("Добавить запись", "Add", "Record")</ul>
    <ul>@Html.ActionLink("Просмотр статистики", "Index", "Statistics")</ul>
    <ul>@Html.ActionLink("Настройки", "Index", "Settings")</ul>
</li>

Cash/Views/Home/List.cshtml
@model IList<Cash.Models.CashflowRecord>

@{
    ViewBag.Title = "Просмотр списка записей";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Просмотр списка записей (это /Views/Home/List.cshtml)</h2>
Внешний вид сейчас не важен, но интерфейс на HTML+CSS+Javascript.
<br/><br/>
Таблица с фиктивными данными. Далее данные будут выводиться из Базы Данных.
<table border="1" cellpadding="10">
    <thead>
    <tr>
        <td>
            Идентификатор
        </td>
        <td>
            Дата
        </td>
        <td>
            Категория
        </td>
        <td>
            Сумма
        </td>
        <td>
            Комментарий
        </td>
    </tr>
    </thead>
    <tbody>
    @for (var i = 0; i < 5; i++)
    {
        <tr>
            <td>
                @i
            </td>
            <td>
                @DateTime.Now.ToString("dd.MM.yyyy")
            </td>
            <td>
                Без категории
            </td>
            <td>
                @{
                    var r = new Random(i + Environment.TickCount);
                    var randomAmount = r.Next(1000000);
                    randomAmount.ToString("n2");
                }
                @randomAmount
            </td>
            <td>
                Комментарий
            </td>
        </tr>        
    }
    
    @foreach (var cashflowRecord in @Model)
    {
        <tr>
            <td>
                @cashflowRecord.Id
            </td>
            <td>
                @cashflowRecord.DateTime.ToString("dd.MM.yyyy")
            </td>
            <td>
                @cashflowRecord.Category.Title
            </td>
            <td>
                @cashflowRecord.Amount
            </td>
            <td>
                @cashflowRecord.Comments
            </td>
        </tr>
    }
    </tbody>
</table>

Cash/Views/Record/Add.cshtml
@{
    ViewBag.Title = "Добавить новую запись";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Добавить новую запись</h2>

Cash/Views/Settings/Index.cshtml
@{
    ViewBag.Title = "Настройки";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Настройки</h2>

<h3>Счета</h3>
@Html.ActionLink("Добавить счет", "Index", "Account")

<h3>Категории</h3>

Cash/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
</head>
<body>
<div>
    @RenderBody()
    
    @Html.ActionLink("На главную", "Index", "Home")
    
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - Paraplaner</p>
        Шаблон оформления задается в Views/Shared/_Layout.cshtml
    </footer>
</div>

</body>
</html>

Cash/Views/Statistics/Index.cshtml
@{
    ViewBag.Title = "Статистика";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Статистика</h2>

Здесь график.

<br/>
<br/>